junit_tests(name='aiqslick',
  dependencies=[
    'src/scala/co/actioniq/luna',
    '3rdparty/org/specs2',
    '3rdparty/com/h2database:h2',
    '3rdparty/com/typesafe:slick',
  ],
  sources=globs('*.scala', 'example/*.scala'),
  strict_deps=True,
)
