junit_tests(name='aiqslick',
  dependencies=[
    'src/scala/co/actioniq/luna',
    'test/resources',
    '3rdparty/org/specs2',
    '3rdparty/org/scala-lang:scala-xml',
    '3rdparty/com/h2database:h2',
    '3rdparty/com/typesafe:slick',
  ],
  sources=['*.scala', 'example/*.scala'],
  strict_deps=True,
)
